version: "2"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    # Import .env data to api environment
    env_file: ./.env
    ports:
      - "${API_LISTENING_PORT}:3000"
    restart: always

    entrypoint: ./docker-entrypoint.sh

    # Link the host src code to the container
    volumes:
      - ./src/:/home/workspace/app/src
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"